encoding: utf-8

# SEO相关信息
title: Haike Nan's Blog
description: 一名IT民工的苦修之旅
keywords: 网络,计算机,思科,网络工程师,CCIE,CCNP
author: Haike Nan
footerText: 'Copyright © 2020-2001 nan.cool'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://nan.cool'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: 

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
#links:
  #- title: 文科中的技术宅
  #  url: https://www.townwang.com
  #- title: Auuu Nya Blog
  #  url: http://mu1er.cn
    
